name: Flask CI

on:
  push:
    branches:
      - "master"
      - "main"
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
      - "release/*"

  pull_request:
    branches:
      - "master"
      - "main"
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Uncomment if you have tests
      # - name: Run tests
      #   run: pytest

